Image slider
IvanaaVasic/shop pull request #1
Opened 2022-12-02 10:16 UTC by IvanaaVasic

Main image slider, made with swiper library. And previous issues from comments fixed

2022-12-02 13:02 UTC, lukalazovic requested changes

2022-12-02 13:02 UTC, lukalazovic commented on src/components/ImagesSlider.tsx
> +        <SwiperSlide>
You could use some API to fetch those images, also you can map SwiperSlide component in array and display data like that

2022-12-02 13:02 UTC, lukalazovic commented on src/components/NavBar.tsx
> +import data from "../../public/json/navData.json";
There is no need for making `navData.json` , you can use it like this

`const data =[
    { "name": "HOME", "path": "/" },
    { "name": "CHECKOUT", "path": "/checkout" },
    { "name": "CONTACT", "path": "/contact" },
    { "name": "PRODUCT", "path": "/product" }
  ]`

2022-12-02 13:02 UTC, lukalazovic commented on src/components/NavBar.tsx
> +import data from "../../public/json/navData.json";
Also lets imagine that this data will come from API, can you make some IData interface?

2022-12-12 02:46 UTC, IvanaaVasic commented on src/components/ImagesSlider.tsx
> +        <SwiperSlide>
This will be done with sanity, as you told me.

2022-12-12 02:51 UTC, IvanaaVasic commented on src/components/NavBar.tsx
> +import data from "../../public/json/navData.json";
It's done.

2022-12-12 03:00 UTC, IvanaaVasic commented on src/components/ImagesSlider.tsx
> +        <SwiperSlide>
I made array with images URLs and map SwiperSlide component.

2022-12-12 14:12 UTC, lukalazovic approved these changes

2022-12-13 16:14 UTC, merged